const express=require("express")
const router=express()
const SpecialController=require("../controllers/specialController.js")// (1-4)
const GeneralController=require("../controllers/generalController.js")// (5-16)

router.get("/login",SpecialController.getLogin) //access (1)
router.post("/login",SpecialController.postLogin) //access (2)
router.get("/register",SpecialController.getRegister) //create (3)
router.post("/register",SpecialController.postRegister) //create (4)
router.get("/home",GeneralController.getHome) //read (5)
router.get("/profile/me",GeneralController.getMyProfile) //read (6)
router.get("/profile/me/edit",GeneralController.getEditMyProfile) //update (7)
router.post("/profile/me/edit",GeneralController.postEditMyProfile) //update (8)
router.get("/profile/:userId",GeneralController.getReadOthersProfile) //read (9)
router.get("/account/:userId",GeneralController.getEditAccount) //update (10)
router.post("/account/:userId",GeneralController.postEditAccount) //update (11)
router.get("/post/add",GeneralController.getAddPost) //create (12)
router.post("/post/add",GeneralController.postAddPost) //create (13)
router.get("/post/:id/edit",GeneralController.getEditPost) //update (14)
router.post("/post/:id/edit",GeneralController.postEditPost) //update (15)
router.get("/post/:id/delete",GeneralController.getDeletePost) //delete (16)

module.exports=router